name: 'archlinux'

on:
  push:
    paths:
      - '.github/workflows/archlinux.yml'
      - 'archlinux/run.sh'
      - 'archlinux/mcode/*'
      - 'archlinux/llvm/*'
      - 'archlinux/gcc/*'
  schedule:
    - cron: '0 0 * * 2,5'

env:
  CI: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        pkg: [
          'mcode',
          'llvm',
          'gcc'
        ]
    steps:

    - uses: actions/checkout@v1

    - run: ./archlinux/run.sh
      env:
        TARGET: ${{ matrix.pkg }}

    - name: Upload package
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.pkg }}
        path: archlinux/${{ matrix.pkg }}/artifacts/*
