name: 'archlinux-git'

on:
  push:
    paths:
      - '.github/workflows/archlinux-git.yml'
      - 'archlinux/run.sh'
      - 'archlinux/mcode-git/*'
      - 'archlinux/llvm-git/*'
      - 'archlinux/gcc-git/*'
  pull_request:
    paths:
      - '.github/workflows/archlinux-git.yml'
      - 'archlinux/run.sh'
      - 'archlinux/mcode/*'
      - 'archlinux/llvm/*'
      - 'archlinux/gcc/*'
  schedule:
    - cron: '0 0 * * 2,5'

env:
  CI: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        ./archlinux/run.sh
      env:
        TARGET: ghdl-git
    - name: Upload package
      uses: actions/upload-artifact@master
      with:
        name: package
        path: archlinux/ghdl-git/tarball
    - name: Upload sources
      uses: actions/upload-artifact@master
      with:
        name: sources
        path: archlinux/ghdl-git/srcs
