name: 'mingw-git'

on:
  push:
    paths:
      - '.github/workflows/mingw-git.yml'
      - 'msys2-mingw/run.sh'
      - 'msys2-mingw/mcode-git/*'
      - 'msys2-mingw/llvm-git/*'
  pull_request:
  schedule:
    - cron: '0 0 * * 2,5'
  workflow_dispatch:

env:
  CI: true

jobs:

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include: [
          #{icon: '🟪', pkg: 'llvm',  bits: '32', arch: i686 }, ! not yet functional
          {icon: '🟦', pkg: 'llvm',  bits: '64', arch: x86_64 },
          {icon: '🟪', pkg: 'mcode', bits: '32', arch: i686,   },
          #{icon: '🟦', pkg: 'mcode', bits: '64', arch: x86_64, }, ! simulation with mcode is not yet supported on win64
        ]
    name: '🚦${{ matrix.sys.icon }} ${{ matrix.sys.pkg }}${{ matrix.sys.bits }} · git'
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_INSTALLS: ${{ matrix.installs }}
      TARGET: ${{ matrix.pkg }}
    steps:

    - name: '${{ matrix.sys.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.installs }}
        update: true
        install: >
          base-devel
          git
          mingw-w64-${{ matrix.arch }}-toolchain
          mingw-w64-${{ matrix.sys.arch }}-diffutils
          mingw-w64-${{ matrix.sys.arch }}-gcc
          mingw-w64-${{ matrix.sys.arch }}-python-pip
          mingw-w64-${{ matrix.sys.arch }}-python-setuptools

    - name: '⚙️ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Build package
      run: ./msys2-mingw/run.sh -b

    - name: '🛠️ Install package and 🐍 Python dependencies'
      run: |
        pacman --noconfirm -U msys2-mingw/${{ matrix.pkg }}/mingw-*ghdl*.pkg.tar.zst
        pip3 install -r testsuite/requirements.txt

    - name: '🚦 Test package'
      name: Test package
      run: ./msys2-mingw/run.sh -t

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.pkg }}
        path: |
          msys2-mingw/${{ matrix.pkg }}/mingw-*ghdl*.pkg.tar.zst
          msys2-mingw/${{ matrix.pkg }}/PKGBUILD
