name: 'mingw'

on:
  push:
    paths:
      - '.github/workflows/mingw.yml'
      - 'msys2-mingw/run.sh'
      - 'msys2-mingw/mcode/*'
      - 'msys2-mingw/llvm/*'
  schedule:
    - cron: '0 0 * * 2,5'

env:
  CI: true

jobs:

  win:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        task: [
          {installs: "MINGW32", pkg: "mcode"},
          #{installs: "MINGW32", pkg: "llvm-git"},  ! Not yet functional
          #{installs: "MINGW64", pkg: "mcode-git"}, ! mcode it not yet supported on win64
          {installs: "MINGW64", pkg: "llvm"},
        ]
    runs-on: windows-latest
    env:
      MINGW_INSTALLS: ${{ matrix.task.installs }}
      TARGET: ${{ matrix.task.pkg }}
    steps:
    - uses: eine/setup-msys2@v0
      with:
        msystem: MSYS
        update: true
    - uses: actions/checkout@v1
    - name: Build and (hopefully) install package
      shell: msys2 {0}
      run: |
        ./msys2-mingw/run.sh -b
    - name: Test package
      shell: msys2 {0}
      run: |
        ./msys2-mingw/run.sh -t
      env:
        MSYSTEM: ${{ matrix.task.installs }}
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.task.pkg }}-package
        path: msys2-mingw/${{ matrix.task.pkg }}/tarball
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.task.pkg }}-sources
        path: msys2-mingw/${{ matrix.task.pkg }}/srcs
